import { $, component$, useStore, useVisibleTask$ } from "@builder.io/qwik";
import { P9ETable } from "~/components/table";

const API_URL = 'http://localhost:9090/api/v1';
const API_URL = 'https://ugcl-429789556411.asia-south1.run.app/api/v1';


export default component$(() => {
  // User table state
  const users = useStore<{ data: any[]; loading: boolean; error: string }>({
    data: [],
    loading: true,
    error: '',
  });
      const fetchUsers = $(async () => {
        users.loading = true;
        users.error = '';
        try {
          const token = localStorage.getItem('token');
          const res = await fetch(`${API_URL}/eway`, {
            headers: { 'Authorization': `Bearer ${token}` },
          });
          if (!res.ok) throw new Error('Failed to fetch: ' + res.statusText);
          const result = await res.json();
          users.data = Array.isArray(result) ? result : (result.users || []);
        } catch (e: any) {
          users.error = e.message || 'Could not load users';
        } finally {
          users.loading = false;
        }
      });

      
        useVisibleTask$(async () => {
          fetchUsers();
        });
    return (
         <P9ETable
                 header={[
  { key: 'billNo', label: 'Bill No' },
  { key: 'generatedDate', label: 'Generated Date', type: 'date', format: 'dd/MM/yyyy' },
  { key: 'generatedBy', label: 'Generated By' },
  { key: 'validUpto', label: 'Valid Upto' },
  { key: 'mode', label: 'Mode' },
  { key: 'type', label: 'Type' },
  { key: 'documentDetails', label: 'Document Details' },
  { key: 'dispatchFrom', label: 'Dispatch From' },
  { key: 'dispatchPincode', label: 'Dispatch Pincode' },
  { key: 'shipToAddress', label: 'Ship To Address' },
  { key: 'shipToPincode', label: 'Ship To Pincode' },
  { key: 'productName', label: 'Product Name' },
  { key: 'pipeDia', label: 'Pipe Dia' },
  { key: 'uom', label: 'UOM' },
  { key: 'quantity', label: 'Quantity' },
  { key: 'hsnCode', label: 'HSN Code' },
  { key: 'taxableAmount', label: 'Taxable Amount' },
  { key: 'transporterIdName', label: 'Transporter Name' },
  { key: 'transporterDocNo', label: 'Transporter Doc No' },
  { key: 'documentDate', label: 'Document Date' },
  { key: 'vehicleNo', label: 'Vehicle No' },
  { key: 'remarks', label: 'Remarks' },
]}
                   data={users.data}
                   title="Users List"
                 />
    );
    }
);